# Generated by Django 4.2.5 on 2023-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'customer'), (2, 'Admin'), (3, 'tailor')], default='', max_length=10),
        ),
    ]
