# Generated by Django 4.2.5 on 2023-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dilna',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
