# Generated by Django 4.2.5 on 2023-09-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_customuser_dilna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dilna',
        ),
    ]
