# Generated by Django 4.2.5 on 2023-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
