# Generated by Django 4.2.5 on 2023-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
