# Generated by Django 4.2.5 on 2023-11-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_measuremententry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasurementEntry',
            new_name='kurtMeasurementEntry',
        ),
    ]
