# Generated by Django 4.2.5 on 2023-11-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_kurtimeasurement_product_kurtimeasurement_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kurtiMeasurement',
            new_name='Measurement',
        ),
    ]
