# Generated by Django 4.2.5 on 2023-11-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_measuremententry_kurtmeasuremententry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kurtMeasurementEntry',
            new_name='kurtiMeasurementEntry',
        ),
    ]
