# Generated by Django 4.2.5 on 2023-11-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_kurtmeasuremententry_kurtimeasuremententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurtimeasuremententry',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
