# Generated by Django 4.2.5 on 2023-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_kurtimeasurement_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='reference_images',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_reference_images/'),
        ),
    ]
