# Generated by Django 4.2.5 on 2023-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_measurement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='reference_images',
        ),
        migrations.AddField(
            model_name='measurement',
            name='neck_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
