# Generated by Django 4.2.5 on 2023-11-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_kurtimeasuremententry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurtimeasuremententry',
            name='product',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
