# Generated by Django 4.2.5 on 2023-11-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='back_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
