# Generated by Django 4.2.5 on 2023-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_measurement_work_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='style_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
