# Generated by Django 4.2.5 on 2023-11-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_measurement_style_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
