# Generated by Django 4.2.5 on 2023-11-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
    ]
