# Generated by Django 4.2.5 on 2023-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_measurement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
