# Generated by Django 4.2.5 on 2023-11-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.order'),
        ),
    ]
