# Generated by Django 4.2.5 on 2023-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_payment_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
