# Generated by Django 4.2.5 on 2023-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Quality Check', 'Quality Check'), ('Assembly', 'Assembly'), ('Cutting', 'Cutting'), ('Fabric dyeing', 'Fabric dyeing'), ('Pattern Making', 'Pattern Making'), ('Measurement and Consultation', 'Measurement and Consultation')], default='Measurement and Consultation', max_length=50),
        ),
    ]
