# Generated by Django 4.2.5 on 2024-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_thread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
