# Generated by Django 4.2.5 on 2024-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_c_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_product',
            name='t_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
