# Generated by Django 4.2.5 on 2024-02-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_interaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
