# Generated by Django 4.2.4 on 2024-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
