# Generated by Django 4.2.4 on 2024-03-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_cart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
