# Generated by Django 4.2.4 on 2024-03-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_cart_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_design', models.CharField(blank=True, max_length=255, null=True)),
                ('back_design', models.CharField(blank=True, max_length=255, null=True)),
                ('sleev_design', models.CharField(blank=True, max_length=255, null=True)),
                ('lining_design', models.CharField(blank=True, max_length=255, null=True)),
                ('work_design', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Add any additional information here.', null=True, verbose_name='Additional Information')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cart')),
            ],
        ),
    ]
