# Generated by Django 4.2.4 on 2024-03-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_remove_cart_design_work_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
    ]
