# Generated by Django 4.2.5 on 2024-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_cart_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customization_added',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
